# Identificacion de sentimientos a partir de videos.
A partir de un listado de videos guardados en google Drive.

### 1. Pasar de video a Fotos.

### Instalacion de librerias

In [1]:
pip install deepface

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting deepface
  Downloading deepface-0.0.79-py3-none-any.whl (49 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.6/49.6 kB 4.9 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from deepface) (1.22.4)
Requirement already satisfied: pandas>=0.23.4 in /usr/local/lib/python3.10/dist-packages (from deepface) (1.5.3)
Requirement already satisfied: tqdm>=4.30.0 in /usr/local/lib/python3.10/dist-packages (from deepface) (4.65.0)
Requirement already satisfied: gdown>=3.10.1 in /usr/local/lib/python3.10/dist-packages (from deepface) (4.6.6)
Requirement already satisfied: Pillow>=5.2.0 in /usr/local/lib/python3.10/dist-packages (from deepface) (8.4.0)
Requirement already satisfied: opencv-python>=4.5.5.64 in /usr/local/lib/python3.10/dist-packages (from deepface) (4.7.0.72)
Requirement already satisfied: tensorflow>=1.9.0 in /usr/local/lib/python3.10/dist-packages (from deepface) (2.12.0)
Requirement already satisfied: keras>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from deepface) (2.12.0)
Requirement already satisfied: Flask>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from deepface) (2.2.4)
Collecting mtcnn>=0.1.0 (from deepface)
  Downloading mtcnn-0.1.1-py3-none-any.whl (2.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 18.8 MB/s eta 0:00:00
Collecting retina-face>=0.0.1 (from deepface)
  Downloading retina_face-0.0.13-py3-none-any.whl (16 kB)
Collecting fire>=0.4.0 (from deepface)
  Downloading fire-0.5.0.tar.gz (88 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.3/88.3 kB 9.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting gunicorn>=20.1.0 (from deepface)
  Downloading gunicorn-20.1.0-py3-none-any.whl (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 7.0 MB/s eta 0:00:00
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from fire>=0.4.0->deepface) (1.16.0)
Requirement already satisfied: termcolor in /usr/local/lib/python3.10/dist-packages (from fire>=0.4.0->deepface) (2.3.0)
Requirement already satisfied: Werkzeug>=2.2.2 in /usr/local/lib/python3.10/dist-packages (from Flask>=1.1.2->deepface) (2.3.0)
Requirement already satisfied: Jinja2>=3.0 in /usr/local/lib/python3.10/dist-packages (from Flask>=1.1.2->deepface) (3.1.2)
Requirement already satisfied: itsdangerous>=2.0 in /usr/local/lib/python3.10/dist-packages (from Flask>=1.1.2->deepface) (2.1.2)
Requirement already satisfied: click>=8.0 in /usr/local/lib/python3.10/dist-packages (from Flask>=1.1.2->deepface) (8.1.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from gdown>=3.10.1->deepface) (3.12.0)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.10/dist-packages (from gdown>=3.10.1->deepface) (2.27.1)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from gdown>=3.10.1->deepface) (4.11.2)
Requirement already satisfied: setuptools>=3.0 in /usr/local/lib/python3.10/dist-packages (from gunicorn>=20.1.0->deepface) (67.7.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.23.4->deepface) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.23.4->deepface) (2022.7.1)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (1.6.3)
Requirement already satisfied: flatbuffers>=2.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (23.3.3)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (0.4.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (0.2.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (1.54.0)
Requirement already satisfied: h5py>=2.9.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (3.8.0)
Requirement already satisfied: jax>=0.3.15 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (0.4.10)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (16.0.0)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (3.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (23.1)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (3.20.3)
Requirement already satisfied: tensorboard<2.13,>=2.12 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (2.12.2)
Requirement already satisfied: tensorflow-estimator<2.13,>=2.12.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (2.12.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (4.5.0)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (1.14.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (0.32.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from astunparse>=1.6.0->tensorflow>=1.9.0->deepface) (0.40.0)
Requirement already satisfied: ml-dtypes>=0.1.0 in /usr/local/lib/python3.10/dist-packages (from jax>=0.3.15->tensorflow>=1.9.0->deepface) (0.1.0)
Requirement already satisfied: scipy>=1.7 in /usr/local/lib/python3.10/dist-packages (from jax>=0.3.15->tensorflow>=1.9.0->deepface) (1.10.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from Jinja2>=3.0->Flask>=1.1.2->deepface) (2.1.2)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.13,>=2.12->tensorflow>=1.9.0->deepface) (2.17.3)
Requirement already satisfied: google-auth-oauthlib<1.1,>=0.5 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.13,>=2.12->tensorflow>=1.9.0->deepface) (1.0.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.13,>=2.12->tensorflow>=1.9.0->deepface) (3.4.3)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.13,>=2.12->tensorflow>=1.9.0->deepface) (0.7.0)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.13,>=2.12->tensorflow>=1.9.0->deepface) (1.8.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->gdown>=3.10.1->deepface) (2.4.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown>=3.10.1->deepface) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown>=3.10.1->deepface) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown>=3.10.1->deepface) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown>=3.10.1->deepface) (3.4)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown>=3.10.1->deepface) (1.7.1)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow>=1.9.0->deepface) (5.3.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow>=1.9.0->deepface) (0.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow>=1.9.0->deepface) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.13,>=2.12->tensorflow>=1.9.0->deepface) (1.3.1)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow>=1.9.0->deepface) (0.5.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.13,>=2.12->tensorflow>=1.9.0->deepface) (3.2.2)
Building wheels for collected packages: fire
  Building wheel for fire (setup.py) ... done
  Created wheel for fire: filename=fire-0.5.0-py2.py3-none-any.whl size=116932 sha256=23a8b695699c60c5b465878e526e98a972ba4218fc44b8f8a2e074b5611d979c
  Stored in directory: /root/.cache/pip/wheels/90/d4/f7/9404e5db0116bd4d43e5666eaa3e70ab53723e1e3ea40c9a95
Successfully built fire
Installing collected packages: gunicorn, fire, mtcnn, retina-face, deepface
Successfully installed deepface-0.0.79 fire-0.5.0 gunicorn-20.1.0 mtcnn-0.1.1 retina-face-0.0.13

### Importación de Librerias

In [2]:
#de Videos a Imagenes.
import cv2
from google.colab import drive

#Extracción de emociones
import pandas as pd
from deepface import DeepFace

# Cantidad de imagenes generadas.
import os
import glob

# Monta la unidad de Google Drive
drive.mount('/content/drive')

Directory  /root /.deepface created
Directory  /root /.deepface/weights created
Mounted at /content/drive

### De Video a Imagenes, de Imagenes a Emociones ;)

In [3]:
# Especifíca la ruta de la carpeta que contiene los videos
ruta_carpeta_videos = '/content/drive/MyDrive/0 New/Validacion DeepFace/DFEW Database/part_1/'  # Cambia esta ruta a la ruta de tu carpeta en Google Colab

# Usamos el módulo glob para buscar archivos con una extensión específica (en este caso, videos con extensión .mp4)
ruta_archivos_videos = os.path.join(ruta_carpeta_videos, '*.mp4')
lista_archivos_videos = glob.glob(ruta_archivos_videos)

# Contamos la cantidad de archivos encontrados  --- m es la cantidad de videos analizadas en el estudio.
m = len(lista_archivos_videos)  # Número de videos en la carpeta.

# Imprimimos el resultado
print(f'La cantidad de archivos de videos en la carpeta es: {m}')

# Creamos la base de datos que almacenará los videos y sus resultados.
df_BD = pd.DataFrame(columns=['Nombre de Imagen', 'angry', 'disgust', 'fear', 'sad', 'neutral', 'surprise', 'happy', 'Video', 'Q_images'])


# re-Asignamos Manualmente la cantidad de videos que queremos extraer. 
#m = 1000

# Loop sobre cada video: Extracción de frames del Video y Computación Afectiva de los frames.
for a in range (1, m+1):    # m es la cantidad de videos.-

    # Abrimos cada video en Google Drive, vamos cambiando el final del nombre del archivo que es un correlativo numérico.
    numero_video = a
    ruta_video = "/content/drive/MyDrive/0 New/Validacion DeepFace/DFEW Database/part_1/" + str(numero_video) + ".mp4"

    # Hacemos la función para extraer y almacenar las imagenes en la carpeta temporal del google Colab (sample data).
    def getFrame(sec):
        vidcap.set(cv2.CAP_PROP_POS_MSEC, sec * 1000)
        hasFrames, image = vidcap.read()
        if hasFrames:
            cv2.imwrite("sample_data/image" + str(count) + ".jpg", image)     # Guardar el frame como archivo JPG
        return hasFrames

    # Abrir el video desde Google Drive
    vidcap = cv2.VideoCapture(ruta_video)

    # Obtener los FPS del video
    fps = vidcap.get(cv2.CAP_PROP_FPS)
    print("FPS del video:", fps)

    # Calculamos de framerate en base a los fps del video.
    frameRate = 1 / fps


    #Hacemos la extraccion y almacenamiento de imagenes.
    sec = 0                     # Segundo desde donde empezamos a extraer
    count = 1
    success = True
    while success:
        sec = sec + frameRate
        sec = round(sec, 2)
        success = getFrame(sec)
        count = count + 1
    # Liberar el objeto VideoCapture y finalizar
    vidcap.release()
    cv2.destroyAllWindows()

    # COMPUTACION AFECTIVA de los frames del Video.
    # Especifica la ruta de la carpeta que contiene las imágenes
    ruta_carpeta = '/content/sample_data'  # Cambia esta ruta a la ruta de tu carpeta en Google Colab

    # Usamos el módulo glob para buscar archivos con una extensión específica (en este caso, imágenes con extensión .jpg)
    ruta_archivos = os.path.join(ruta_carpeta, '*.jpg')
    lista_archivos = glob.glob(ruta_archivos)

    # Contamos la cantidad de archivos encontrados  --- N es la cantidad de imagenes analizadas en el video.
    n = len(lista_archivos) #numero de imagenes en la carpeta.

    # Imprimimos el resultado
    print(f'La cantidad de archivos de imágenes en la carpeta es: {n}')

    # --------------------------------------------------------------------------------------------
    #EXTRACCION DE EMOCIONES A PARTIR DE IMAGENES.
    # Crear una lista para almacenar los datos
    data = []

    # Bucle para analizar cada imagen y guardar los datos en la lista (data)
    for i in range(1, n+1):     # n es la cantidad de archivos encontrados en la carpeta con formato de imagen (son los frames extraídos).
        # Analizamos la imagen con DeepFace
        img_path = f"sample_data/image{i}.jpg"  # Ruta de la imagen
        objs = DeepFace.analyze(img_path=img_path, actions=['emotion'], enforce_detection=False)
        
        # Obtener el nombre de la imagen y las emociones analizadas
        nombre_imagen = f"imagen{i}.jpg"
        emociones = objs[0]['emotion']
        
        # Agregar los datos a la lista
        data.append([nombre_imagen, emociones])
        
    # Crear un DataFrame de pandas a partir de la lista de datos
    df = pd.DataFrame(data, columns=['Nombre de Imagen', 'Emociones'])

    # Aplicar una función para convertir el diccionario de emociones en columnas individuales (una lista de varios elementos con valores a varias columnas).
    df = df.join(df['Emociones'].apply(pd.Series))

    # Eliminar la columna 'Emociones' original
    df = df.drop('Emociones', axis=1)

    # Redondear todos los valores en el DataFrame a un decimal.
    df = df.round(1)

    # Lista con el nuevo orden de las columnas.
    nuevo_orden = ['Nombre de Imagen', 'happy', 'sad', 'neutral', 'angry',  'surprise', 'disgust', 'fear' ] #'angry', 'disgust', 'fear', 'sad', 'neutral', 'surprise', 'happy']

    # Reordenamos las columnas en el DataFrame.
    df = df[nuevo_orden]

    # Agregamos el identificador del video.
    df=df.assign(Video=numero_video)

    # Agregamos columna que indica cantidad de imagenes extraidas del Video.
    df=df.assign(Q_images=n)

    # Agregamos dataframe de emociones del video (df) al dataframe que almacena los resultados de todos los videos (df2).
    df_BD = df_BD.append(df)

    # Eliminar archivos jpg de la carpeta. nombre carpeta. Con esto terminamos el loop.
    # Ruta a la carpeta que contiene las imágenes JPG
    ruta_carpeta = '/content/sample_data/'

    # Obtener la lista de archivos en la carpeta.
    archivos = os.listdir(ruta_carpeta)

    # Iterar sobre los archivos y eliminar las imágenes en formato JPG.
    for archivo in archivos:
        if archivo.endswith('.jpg'):
            ruta_archivo = os.path.join(ruta_carpeta, archivo)
            os.remove(ruta_archivo)

#Imprimimos el resultado
df_BD

La cantidad de archivos de videos en la carpeta es: 1603
FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 23
facial_expression_model_weights.h5 will be downloaded...

Downloading...
From: https://github.com/serengil/deepface_models/releases/download/v1.0/facial_expression_model_weights.h5
To: /root/.deepface/weights/facial_expression_model_weights.h5
100%|██████████| 5.98M/5.98M [00:00<00:00, 64.8MB/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  1.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  1.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.39it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.00it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.08it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.04it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.53it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.87it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.29it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.16it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.25it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.27it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  1.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.64it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.10it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 22

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.55it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.16it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.05it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.12it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.56it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.64it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  2.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  1.86it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 17

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.76it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.34it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.93it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 6

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.84it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.66it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.77it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 4

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.35it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  2.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.28it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.59it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 13

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.47it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 18

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.36it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.84it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.55it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.56it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.99it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 43

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.91it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.27it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.38it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.13it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.17it/s]

FPS del video: 29.97002997002997
La cantidad de archivos de imágenes en la carpeta es: 42

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.34it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.85it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 31

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.37it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 17

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.65it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 22

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.15it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.13it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.34it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 17

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.45it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.68it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 4

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.31it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.15it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.81it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.36it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 4

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.40it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 27

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.64it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 14

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.65it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.12it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.23it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.72it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.97it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.37it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.54it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 20

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.34it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.83it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.63it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.50it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.83it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.10it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.27it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.70it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 17

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.39it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 17

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.68it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.60it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.13it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.45it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 12

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  1.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.04it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.49it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.64it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.39it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 31

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.12it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.37it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.17it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.67it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.42it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.05it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 16

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.88it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.12it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.94it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.42it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 17

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 14

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.32it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.52it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.96it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.94it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 31

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.30it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.18it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.23it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.87it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.94it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.06it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 14

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.97it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 6

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.43it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.94it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.92it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.07it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.56it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.21it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.54it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.73it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 17

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.12it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 44

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.25it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.85it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.80it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.56it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.23it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.33it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.54it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.92it/s]

FPS del video: 29.97
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.44it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.00it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 13

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.49it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.09it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  1.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.19it/s]

FPS del video: 29.97
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.03it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 13

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.58it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 21

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.24it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.86it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.81it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 20

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.38it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.62it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.41it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.22it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 18

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.30it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.92it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.39it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.97it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.75it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.68it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 16

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.81it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.99it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.44it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.32it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.47it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.23it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.11it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 13

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.08it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 35

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.32it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 16

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.54it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.70it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.39it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.26it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.49it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.20it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 21

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.06it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.58it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.27it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.13it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.59it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.34it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.31it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.41it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 18

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.62it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 31

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.47it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.77it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  2.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 13

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.50it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.42it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.77it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.52it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 12

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.93it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.35it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 17

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.25it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.55it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.02it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.58it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.50it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.82it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 35

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 13

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.02it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.95it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.85it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.89it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.27it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.84it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.07it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 6

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.18it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.32it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.88it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.55it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.26it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.45it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.51it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.56it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.89it/s]

FPS del video: 29.97
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]

FPS del video: 29.97
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.62it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.53it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.25it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.86it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.98it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 14

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.20it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.62it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.28it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.05it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.89it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  1.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.99it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.93it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.15it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 31

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.08it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.55it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.59it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.27it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 17

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.22it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.54it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.28it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 13

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.45it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.54it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.02it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.33it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.19it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 43

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.20it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.95it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.58it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.16it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.34it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 16

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.83it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 29

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.08it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.98it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 13

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.47it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.04it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.23it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.03it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 21

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  1.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 17

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.41it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 50

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.79it/s]

FPS del video: 29.97
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.20it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.54it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.83it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.23it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 6

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.29it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.06it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.92it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.69it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 16

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.49it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.61it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.55it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.88it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.80it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.16it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.32it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 27

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.63it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.97it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.74it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.50it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 24

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.40it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 47

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.39it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.20it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.35it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.08it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.99it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.63it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 22

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.45it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 35

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.85it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.48it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.02it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.36it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.39it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.28it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.51it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.48it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 14

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.34it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 17

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  2.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.86it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.36it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.88it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.35it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 12

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.78it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.46it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.84it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.35it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 13

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 24

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 4

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.63it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 18

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.37it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 21

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.34it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 35

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.10it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 14

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.71it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 28

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.02it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.64it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.92it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 20

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.21it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 4

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.47it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 6

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.60it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 16

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.47it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.81it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 12

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.89it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.10it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 55

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.56it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.25it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.80it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  3.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 22

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.77it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  1.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.05it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 6

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.76it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]

FPS del video: 23.964
La cantidad de archivos de imágenes en la carpeta es: 21

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.32it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.71it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.38it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.70it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.08it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.23it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.39it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.17it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 16

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.17it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.96it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.55it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.97it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.44it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.64it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 14

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.58it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 12

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.55it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 12

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.20it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.29it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.34it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.72it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.39it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.41it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.93it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.96it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.66it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 38

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.56it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.73it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 12

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.80it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.66it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 18

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.78it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  1.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 13

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.27it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.83it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 13

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.18it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.66it/s]

FPS del video: 29.97
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.50it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.47it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 6

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.25it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 27

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.94it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 14

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.90it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.08it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.46it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.33it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 27

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.46it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.27it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.05it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.83it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.78it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 6

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.85it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.21it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.55it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.67it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 6

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.78it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 26

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.86it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 27

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.59it/s]

FPS del video: 29.97
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.53it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.71it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 14

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.17it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 4

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.70it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 14

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  2.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 16

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.76it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 6

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 16

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.31it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.82it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.30it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 27

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.44it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.79it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.07it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.10it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.03it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 6

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.39it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 16

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.41it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.30it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.72it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]

FPS del video: 17.982
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 6

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 27

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.08it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 4

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.94it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 6

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.15it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.41it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 31

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.95it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.48it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 39

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 18

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.46it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.99it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 35

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  1.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.54it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 4

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.01it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.27it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.71it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.44it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 16

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.82it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.01it/s]

FPS del video: 19.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.05it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.87it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.78it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.91it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.61it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 35

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]

FPS del video: 29.97
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.05it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 17

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.67it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.42it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.57it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.01it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.12it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.03it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 12

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 24

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.40it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.30it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.53it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.82it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.22it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 27

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.71it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 13

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  1.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 14

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.26it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.77it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]

FPS del video: 23.0
La cantidad de archivos de imágenes en la carpeta es: 6

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.79it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 17

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.64it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 21

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 35

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  3.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.61it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  2.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  2.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.08it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  3.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  3.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.17it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  2.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  3.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  3.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.95it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.28it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.98it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]

FPS del video: 29.97
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.68it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 12

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  3.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.04it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 13

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.69it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 6

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.93it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.34it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 18

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.34it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.89it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.41it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.91it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.05it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.32it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 14

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.96it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.38it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 13

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.51it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 4

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.42it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.65it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 6

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 16

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.12it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.55it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.11it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 13

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.21it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 12

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.20it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.57it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]

FPS del video: 29.97
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.91it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 27

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.47it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 6

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]

FPS del video: 29.97
La cantidad de archivos de imágenes en la carpeta es: 12

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.41it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 13

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.74it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 31

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.87it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 14

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.89it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 6

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.75it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.16it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.79it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.68it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]

FPS del video: 19.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 37

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.99it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.62it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.80it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 35

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 12

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.80it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 27

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.89it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 4

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.10it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 16

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.16it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.70it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.11it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.66it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.99it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  1.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.90it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 46

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.77it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.91it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.50it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 16

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.62it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.71it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 18

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.80it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.41it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.15it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 18

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.55it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.77it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.36it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 12

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]

FPS del video: 20.0
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.50it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.02it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 12

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.17it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 39

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.25it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.22it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.90it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 31

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.18it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 18

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.50it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.76it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 33

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.46it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.91it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 12

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.08it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 21

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  1.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 6

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.24it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.92it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.56it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.25it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.30it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.06it/s]

FPS del video: 15.0
La cantidad de archivos de imágenes en la carpeta es: 35

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 31

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.95it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 14

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.03it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 12

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]

FPS del video: 29.97002997002997
La cantidad de archivos de imágenes en la carpeta es: 21

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.19it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 6

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.57it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]

FPS del video: 29.97002997002997
La cantidad de archivos de imágenes en la carpeta es: 12

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.13it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.98it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 27

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.41it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 43

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.62it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.40it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 14

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 4

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.04it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.11it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]

FPS del video: 29.97002997002997
La cantidad de archivos de imágenes en la carpeta es: 14

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 12

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.19it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.22it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  1.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.54it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 6

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.70it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.21it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 12

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.31it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.82it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 27

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.61it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.72it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.96it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.70it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.89it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.06it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.26it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.45it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.26it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.22it/s]

FPS del video: 29.97
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.13it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.32it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.76it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.03it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.44it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.03it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 21

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.69it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.64it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.75it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.12it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 119

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.15it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.41it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.32it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.77it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.92it/s]

FPS del video: 23.0
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.03it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 17

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.33it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.54it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.06it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  2.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.26it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.27it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 12

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.66it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.86it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.99it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 35

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.06it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.97it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 17

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.43it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.23it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.93it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.73it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.93it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.35it/s]

FPS del video: 15.0
La cantidad de archivos de imágenes en la carpeta es: 13

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 31

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  3.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 6

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.50it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 21

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.92it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.82it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.93it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.67it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.61it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.33it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.73it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 31

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.61it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 39

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.07it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 20

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.29it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.68it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.06it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.66it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 21

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.77it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 4

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 12

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 13

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.27it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.36it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.74it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.55it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 34

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  1.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  2.70it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.10it/s]

FPS del video: 29.97002997002997
La cantidad de archivos de imágenes en la carpeta es: 13

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.77it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.18it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.27it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 20

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.61it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 27

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.94it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.46it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.07it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.64it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.05it/s]

FPS del video: 29.97
La cantidad de archivos de imágenes en la carpeta es: 43

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.58it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.53it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.51it/s]

FPS del video: 15.0
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]

FPS del video: 29.97002997002997
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.40it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 13

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.47it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 13

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.30it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 29

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 21

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 6

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.68it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 16

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.42it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.17it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.57it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 17

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  1.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.71it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.17it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]

FPS del video: 29.97
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.18it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 13

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]

FPS del video: 29.97002997002997
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 16

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 39

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.47it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 18

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.57it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 14

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.40it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.69it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.72it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.15it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.31it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 16

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 39

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.85it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 32

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 14

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.12it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 22

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.96it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.44it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.71it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.48it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.74it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 31

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.37it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 18

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  1.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.51it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 27

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.28it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.99it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.59it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.13it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 14

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.72it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.94it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 12

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.47it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.37it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]

FPS del video: 29.97
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 39

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 26

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 51

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.09it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 13

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.38it/s]

FPS del video: 23.976042590949422
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.22it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.78it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.22it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.03it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.35it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.95it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.16it/s]

FPS del video: 29.97
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.44it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 18

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.81it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.08it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 27

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.82it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 4

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.77it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.68it/s]

FPS del video: 29.97002997002997
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.16it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 14

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.44it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]

FPS del video: 19.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 13

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 14

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.87it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]

FPS del video: 23.0
La cantidad de archivos de imágenes en la carpeta es: 18

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  1.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.90it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.74it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 6

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.08it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.03it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.65it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 27

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.39it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 14

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 13

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.51it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.75it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 24

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.87it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.06it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.72it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.48it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.85it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.02it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 16

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.66it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.93it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.95it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]

FPS del video: 29.97002997002997
La cantidad de archivos de imágenes en la carpeta es: 17

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.85it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.94it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.29it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.14it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.08it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 13

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.17it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 20

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.18it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.07it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.92it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.22it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 12

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.26it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]

FPS del video: 29.97
La cantidad de archivos de imágenes en la carpeta es: 13

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 31

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.95it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.42it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]

FPS del video: 29.97002997002997
La cantidad de archivos de imágenes en la carpeta es: 18

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.03it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  1.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.84it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]

FPS del video: 29.97
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.51it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 20

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.58it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.83it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 63

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.27it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.26it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.90it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.13it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 18

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.49it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 13

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 13

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.70it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.50it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.61it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 4

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.36it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 24

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.95it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.07it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.93it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 6

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.23it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.02it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.28it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.66it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 13

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 12

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.26it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 14

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 17

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.71it/s]

FPS del video: 29.97002997002997
La cantidad de archivos de imágenes en la carpeta es: 14

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.90it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 16

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]

FPS del video: 19.0
La cantidad de archivos de imágenes en la carpeta es: 27

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.96it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 27

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  1.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.24it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 13

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.18it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 6

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.15it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 28

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 17

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 27

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.38it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.65it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 14

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.23it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.59it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.22it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.41it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.00it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 27

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.29it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.06it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 20

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 39

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.54it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.29it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.73it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 4

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.84it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.06it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 13

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 6

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.61it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.89it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 27

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.56it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  1.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.35it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 31

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.57it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.08it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.07it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.27it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.32it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.58it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.50it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.37it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.18it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.87it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.76it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.29it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.68it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.25it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 17

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 6

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.02it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 26

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.15it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.99it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.87it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.38it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.13it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 47

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.52it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 27

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.13it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.47it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.69it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.04it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 22

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.38it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  1.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.54it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.09it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 12

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.19it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.15it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.75it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.68it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.23it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.72it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.98it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]

FPS del video: 29.97002997002997
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]

FPS del video: 29.97002997002997
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 14

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]

FPS del video: 29.97
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 13

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.92it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 25

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.77it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 2

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.54it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.84it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 12

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.65it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]

FPS del video: 29.97
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.54it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 27

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.78it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.44it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 14

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.55it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 27

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.59it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.03it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.13it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.18it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 12

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.88it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 6

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.63it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.95it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 19

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.30it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  1.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.79it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.70it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.81it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.62it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 17

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  3.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.40it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.56it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.49it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.65it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.44it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.00it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.78it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 23

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 13

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.34it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 10

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 17

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.02it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.82it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.80it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.44it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 3

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.77it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 9

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 4

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.14it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 16

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.91it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 39

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 16

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.41it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 17

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.51it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.89it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 15

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]

FPS del video: 25.0
La cantidad de archivos de imágenes en la carpeta es: 39

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 39

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  4.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.95it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.50it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 14

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.54it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.86it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.38it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 11

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.67it/s]

FPS del video: 23.976023976023978
La cantidad de archivos de imágenes en la carpeta es: 8

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.36it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 5

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]

FPS del video: 24.0
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.91it/s]

FPS del video: 23.976
La cantidad de archivos de imágenes en la carpeta es: 7

Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  7.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  9.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 10.09it/s]

FPS del video: 0.0
La cantidad de archivos de imágenes en la carpeta es: 0

ValueError: ignored

### Guardamos la BD

In [4]:
#Guardamos la Base de datos.
ruta_video

'/content/drive/MyDrive/0 New/Validacion DeepFace/DFEW Database/part_1/1601.mp4'

In [5]:
import pandas as pd

# Guardamos el DataFrame df2.
# Ruta de destino en Google Colab
ruta_destino = '/content/sample_data/df_BD.csv'
# Guardar el DataFrame como archivo CSV
df_BD.to_csv(ruta_destino, index=False)
# Ruta de destino en Google Colab 
ruta_destino = '/content/sample_data/df_BD.xlsx'
# Guardar el DataFrame como archivo Excel
df_BD.to_excel(ruta_destino, index=False)

In [7]:
#copiamos la dataframe en df2.
df2 = df_BD.copy()

### Promedios de emocion por Video.

In [9]:
### Promedios de emocion por Video.
# Columnas de emociones
columnas_emociones = ['happy', 'sad', 'neutral', 'angry',  'surprise', 'disgust', 'fear' ]
# Sumar los valores de las columnas de emociones para cada video y la divide por la cantidad de imagenes del video (valor de cualquier casilla de Q_imagenes del video)
df_mean = df2.groupby('Video')[columnas_emociones].mean().reset_index()
print(df_mean)

      Video      happy        sad    neutral      angry   surprise   disgust  \
0         1   0.000000  43.452174   2.413043   0.026087  14.447826  0.000000
1         2   0.000000  52.636364  39.290909   0.418182   0.309091  0.000000
2         3   0.000000  74.931579  13.136842   0.000000   0.000000  0.000000
3         4   0.000000  91.228571   0.814286   0.842857   0.014286  0.000000
4         5   0.000000  50.630000  11.370000  28.760000   1.110000  0.000000
...     ...        ...        ...        ...        ...        ...       ...
1595   1596  39.245455   0.000000   0.000000  45.663636   0.000000  0.000000
1596   1597   5.687500  23.375000  29.437500  18.212500   2.537500  0.000000
1597   1598  59.480000   2.000000   0.000000  38.220000   0.000000  0.000000
1598   1599  31.257143  11.700000  12.771429   3.014286   0.385714  0.271429
1599   1600   0.257143  79.014286   0.657143   6.800000   1.614286  0.000000

           fear
0     39.656522
1      7.336364
2     11.921053
3      7.085714
4      8.120000
...         ...
1595  15.127273
1596  20.750000
1597   0.280000
1598  40.628571
1599  11.657143

[1600 rows x 8 columns]

### Conteo  //  Contar Casos con prob mayor a un umbral. //

In [13]:
# Columnas de emociones
columnas_emociones = ['happy', 'sad', 'neutral', 'angry',  'surprise', 'disgust', 'fear' ]
# Umbral para filtrar los valores de las emociones
umbral = 60
# Aplicar la máscara booleana y contar las veces que se supera el umbral para cada video
df_cont_u60 = df2[columnas_emociones].applymap(lambda x: 1 if x > umbral else 0).groupby(df2['Video']).sum().reset_index()
# Imprimir el DataFrame de resultados
df_cont_u60

      Video  happy  sad  neutral  angry  surprise  disgust  fear
0         1      0   11        0      0         3        0     5
1         2      0    3        3      0         0        0     1
2         3      0   13        2      0         0        0     1
3         4      0    7        0      0         0        0     0
4         5      0    5        1      2         0        0     0
...     ...    ...  ...      ...    ...       ...      ...   ...
1595   1596      3    0        0      4         0        0     0
1596   1597      0    2        2      2         0        0     2
1597   1598      3    0        0      2         0        0     0
1598   1599      2    0        0      0         0        0     1
1599   1600      0    7        0      0         0        0     0

[1600 rows x 8 columns]

### Respaldamos la BD del Resumen de las observaciones de los videos en formato csv y xlsx.

In [15]:
# Guardamos la BD en .csv y .xlsx .-
import pandas as pd

# Ruta de destino en carpeta temporal de Google Colab sample_data
ruta_destino = '/content/sample_data/nuevo_dataframedf_BD.csv'

# Guardar el DataFrame como archivo CSV
nuevo_dataframe.to_csv(ruta_destino, index=False)

# Ruta de destino en Google Colab
ruta_destino = '/content/sample_data/nuevo_dataframedf_BD.xlsx'

# Guardar el DataFrame como archivo Excel
nuevo_dataframe.to_excel(ruta_destino, index=False)

### Eliminamos valores perdidos o NaNs

In [25]:
# Eliminar los valores NaN en la columna 'Columna1'.
nuevo_dataframe_sin_nans = nuevo_dataframe2.dropna(subset=['happy_mean', 'sad_mean','happy_sum', 'neutral_mean', 'angry_mean', 'surprise_mean', 'disgust_mean', 'fear_mean', ])
# Mostrar el DataFrame sin los valores NaN.
nuevo_dataframe_sin_nans.head(5)

,Video,happy_sum,sad_sum,neutral_sum,angry_sum,surprise_sum,disgust_sum,fear_sum,happy_mean,sad_mean,...,disgust_cont_u60,fear_cont_u60,1happy,2sad,3neutral,4angry,5surprise,6disgust,7fear,label
0,1,0.0,999.4,55.5,0.6,332.3,0.0,912.1,0.0,43.452174,...,0.0,5.0,0,6,4,0,0,0,0,2
1,2,0.0,579.0,432.2,4.6,3.4,0.0,80.7,0.0,52.636364,...,0.0,1.0,0,2,8,0,0,0,0,3
2,3,0.0,1423.7,249.6,0.0,0.0,0.0,226.5,0.0,74.931579,...,0.0,1.0,3,1,1,0,5,0,0,0
3,4,0.0,638.6,5.7,5.9,0.1,0.0,49.6,0.0,91.228571,...,0.0,0.0,0,6,3,1,0,0,0,2
4,5,0.0,506.3,113.7,287.6,11.1,0.0,81.2,0.0,50.630000,...,0.0,0.0,0,2,2,1,4,0,1,0