In [20]:
import os
import glob
import cv2
import pandas as pd
from deepface import DeepFace

# Especifíca la ruta de la carpeta que contiene los videos
ruta_carpeta_videos = "C:/Users/franc/Desktop/DeepVideoFER/Gestion"
ruta_temp_data = os.path.join(ruta_carpeta_videos, "temp_data")

# Asegurarse de que la carpeta temp_data exista
if not os.path.exists(ruta_temp_data):
    os.makedirs(ruta_temp_data)

# Usamos el módulo glob para buscar archivos con una extensión específica (en este caso, videos con extensión .mp4)
ruta_archivos_videos = os.path.join(ruta_carpeta_videos, '*.mp4')
lista_archivos_videos = glob.glob(ruta_archivos_videos)

# Contamos la cantidad de archivos encontrados
m = len(lista_archivos_videos)  # Número de videos en la carpeta.

# Imprimimos el resultado
print(f'La cantidad de archivos de videos en la carpeta es: {m}')

# Creamos la base de datos que almacenará los videos y sus resultados.
df_BD = pd.DataFrame(columns=['Nombre de Imagen', 'angry', 'disgust', 'fear', 'sad', 'neutral', 'surprise', 'happy', 'Video', 'Q_images'])


# Lista todos los archivos en la carpeta
archivos = os.listdir(ruta_carpeta_videos)

# Filtra solo aquellos que terminan en .mp4
videos = [archivo for archivo in archivos if archivo.endswith('.mp4')]

for video in videos:
    ruta_video = os.path.join(ruta_carpeta_videos, video)

    def getFrame(sec):
        vidcap.set(cv2.CAP_PROP_POS_MSEC, sec * 1000)
        hasFrames, image = vidcap.read()
        if hasFrames:
            cv2.imwrite(os.path.join(ruta_temp_data, "image" + str(count) + ".jpg"), image)
        return hasFrames

    vidcap = cv2.VideoCapture(ruta_video)

    # Obtener los FPS del video
    fps = vidcap.get(cv2.CAP_PROP_FPS)
    print("FPS del video:", fps)

    # Calculamos de framerate en base a los fps del video.
    frameRate = 0.25  # 1 / fps

    sec = 0
    count = 1
    success = True
    while success:
        sec = sec + frameRate
        sec = round(sec, 2)
        success = getFrame(sec)
        count = count + 1

    vidcap.release()
    cv2.destroyAllWindows()

    # Computación afectiva de los frames del video.
    ruta_archivos = os.path.join(ruta_temp_data, '*.jpg')
    lista_archivos = glob.glob(ruta_archivos)
    n = len(lista_archivos)

    print(f'La cantidad de archivos de imágenes en la carpeta es: {n}')

    data = []

    for i in range(1, n+1):
        img_path = os.path.join(ruta_temp_data, f"image{i}.jpg")
        objs = DeepFace.analyze(img_path=img_path, actions=['emotion'], enforce_detection=False)

        nombre_imagen = f"imagen{i}.jpg"
        emociones = objs[0]['emotion']

        data.append([nombre_imagen, emociones])

    df = pd.DataFrame(data, columns=['Nombre de Imagen', 'Emociones'])
    df = df.join(df['Emociones'].apply(pd.Series))
    df = df.drop('Emociones', axis=1)
    df = df.round(1)
    nuevo_orden = ['Nombre de Imagen', 'happy', 'sad', 'neutral', 'angry',  'surprise', 'disgust', 'fear']
    df = df[nuevo_orden]
    df = df.assign(Video=video.split('.')[0])  # Esto extraerá el nombre ej: "video1" de "video1.mp4"
    df = df.assign(Q_images=n)
    
    df_BD = pd.concat([df_BD, df], ignore_index=True)

    archivos = os.listdir(ruta_temp_data)
    for archivo in archivos:
        if archivo.endswith('.jpg'):
            ruta_archivo = os.path.join(ruta_temp_data, archivo)
            os.remove(ruta_archivo)

La cantidad de archivos de videos en la carpeta es: 2
FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 360

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 15.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 14.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 15.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 15.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 15.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.59it/s]

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 15.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 15.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 15.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 15.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.01it/s]

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 15.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 15.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.24it/s]

FPS del video: 30.0
La cantidad de archivos de imágenes en la carpeta es: 151

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.34it/s]

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.53it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.96it/s]

In [30]:
import os
import glob
import cv2
import pandas as pd
from deepface import DeepFace

def analizar_emociones_videos(ruta_carpeta_videos):

    ruta_temp_data = os.path.join(ruta_carpeta_videos, "temp_data")

    if not os.path.exists(ruta_temp_data):
        os.makedirs(ruta_temp_data)

    lista_archivos_videos = glob.glob(os.path.join(ruta_carpeta_videos, '*.mp4'))
    m = len(lista_archivos_videos)

    df_BD = pd.DataFrame(columns=['Nombre de Imagen', 'angry', 'disgust', 'fear', 'sad', 'neutral', 'surprise', 'happy', 'Video', 'Q_images'])

    videos = [archivo for archivo in os.listdir(ruta_carpeta_videos) if archivo.endswith('.mp4')]

    for video in videos:
        ruta_video = os.path.join(ruta_carpeta_videos, video)

        def getFrame(sec):
            vidcap.set(cv2.CAP_PROP_POS_MSEC, sec * 1000)
            hasFrames, image = vidcap.read()
            if hasFrames:
                cv2.imwrite(os.path.join(ruta_temp_data, "image" + str(count) + ".jpg"), image)
            return hasFrames

        vidcap = cv2.VideoCapture(ruta_video)
        fps = vidcap.get(cv2.CAP_PROP_FPS)
        frameRate = 0.25  # 1 / fps
        sec = 0
        count = 1
        success = True

        while success:
            sec = sec + frameRate
            sec = round(sec, 2)
            success = getFrame(sec)
            count = count + 1

        vidcap.release()
        cv2.destroyAllWindows()

        lista_archivos = glob.glob(os.path.join(ruta_temp_data, '*.jpg'))
        n = len(lista_archivos)

        data = []

        for i in range(1, n+1):
            img_path = os.path.join(ruta_temp_data, f"image{i}.jpg")
            objs = DeepFace.analyze(img_path=img_path, actions=['emotion'], enforce_detection=False)

            nombre_imagen = f"imagen{i}.jpg"
            emociones = objs[0]['emotion']

            data.append([nombre_imagen, emociones])

        df = pd.DataFrame(data, columns=['Nombre de Imagen', 'Emociones'])
        df = df.join(df['Emociones'].apply(pd.Series))
        df = df.drop('Emociones', axis=1)
        df = df.round(1)
        nuevo_orden = ['Nombre de Imagen', 'happy', 'sad', 'neutral', 'angry',  'surprise', 'disgust', 'fear']
        df = df[nuevo_orden]
        df = df.assign(Video=video.split('.')[0])
        df = df.assign(Q_images=n)
    
        df_BD = pd.concat([df_BD, df], ignore_index=True)

        archivos = os.listdir(ruta_temp_data)
        for archivo in archivos:
            if archivo.endswith('.jpg'):
                ruta_archivo = os.path.join(ruta_temp_data, archivo)
                os.remove(ruta_archivo)

    return df_BD

In [35]:
# Para usar la función:
resultado = analizar_emociones_videos("C:/Users/franc/Desktop/DeepVideoFER/Gestion")
print(resultado)

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 23.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 23.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 24.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 15.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 24.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 24.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 23.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.40it/s]

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 23.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.68it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 25.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 15.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.43it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.45it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.67it/s]

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.50it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.49it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.82it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.51it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.73it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.42it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.25it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.67it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.57it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.77it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.87it/s]

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 23.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.75it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 23.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.60it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 13.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.52it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 24.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.39it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 23.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.44it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.00it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.46it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 24.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.80it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.69it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.62it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.35it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.83it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.85it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.76it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 15.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 15.48it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 15.37it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.02it/s]

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 15.91it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.64it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.41it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.55it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.10it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.93it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.86it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.98it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.81it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.61it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.58it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 25.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 16.56it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.27it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.65it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.31it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 24.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.32it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.36it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.24it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.13it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.30it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 24.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.66it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.54it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.04it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.92it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 24.95it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 25.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 25.16it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.90it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.59it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.19it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.18it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.70it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.34it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.94it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.09it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.29it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.96it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.07it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.63it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.26it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.71it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.22it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.88it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  3.89it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 17.03it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 23.78it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.06it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.87it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.02it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.11it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.97it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.01it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 19.99it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.21it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.07it/s]

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.33it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.38it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.15it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 21.28it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.23it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 23.79it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 23.47it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.05it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 22.14it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 11.40it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.84it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 18.20it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.12it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.72it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.08it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.17it/s]
Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 20.01it/s]

    Nombre de Imagen  angry  disgust  fear   sad  neutral  surprise  happy  \
0        imagen1.jpg   15.3     54.2   5.8  16.8      7.7       0.1    0.1
1        imagen2.jpg    0.0      0.0   0.8  93.8      0.1       0.0    5.3
2        imagen3.jpg    0.3      0.0   5.1   0.5      0.5       1.7   92.0
3        imagen4.jpg    0.0      0.0   0.1   0.0      0.0       0.0   99.8
4        imagen5.jpg   41.1      0.0   0.5  46.1      0.0       0.0   12.3
..               ...    ...      ...   ...   ...      ...       ...    ...
657    imagen147.jpg    0.0      0.0   0.5   1.3     98.2       0.0    0.0
658    imagen148.jpg    0.0      0.0   1.7   2.1     96.1       0.1    0.0
659    imagen149.jpg    0.0      0.0   0.7   0.1     98.9       0.2    0.0
660    imagen150.jpg    0.0      0.0   0.1  98.6      1.4       0.0    0.0
661    imagen151.jpg    0.1      0.0   1.9  97.4      0.6       0.0    0.0

             Video Q_images
0            test1      360
1            test1      360
2            test1      360
3            test1      360
4            test1      360
..             ...      ...
657  videoplayback      151
658  videoplayback      151
659  videoplayback      151
660  videoplayback      151
661  videoplayback      151

[662 rows x 10 columns]

In [36]:
def obtener_promedios(df):
    """ 
    Calcula el promedio de las emociones por video.
    
    Parámetros:
    df (DataFrame): DataFrame que contiene las emociones y el nombre del video.
    
    Retorna:
    DataFrame: Promedios de las emociones por video.
    """
    # Lista de columnas de emociones
    columnas_emociones = ['angry', 'disgust', 'fear', 'sad', 'neutral', 'surprise', 'happy']
    
    # Seleccionamos solo las columnas de emociones y 'Video'
    datos_emociones = df[['Video'] + columnas_emociones]
    
    # Agrupar por la columna 'Video' y calcular el promedio para cada emoción
    resultados_promedio = datos_emociones.groupby('Video').mean()
    
    return resultados_promedio

In [39]:
resultados2 = obtener_promedios(df_BD)
print(resultados2)

                   angry   disgust       fear        sad  neutral  surprise  \
Video
test1           7.116944  0.759444  17.637778  12.276944  23.6075  5.369722
videoplayback  14.362914  0.113245  14.883444  30.638411  17.8000  1.043046

                   happy
Video
test1          33.220278
videoplayback  21.148344

In [21]:
df

,Nombre de Imagen,happy,sad,neutral,angry,surprise,disgust,fear,Video,Q_images
0,imagen1.jpg,0.1,48.0,6.5,0.0,0.0,0.0,45.4,videoplayback,151
1,imagen2.jpg,0.1,48.0,6.5,0.0,0.0,0.0,45.4,videoplayback,151
2,imagen3.jpg,0.1,48.0,6.5,0.0,0.0,0.0,45.4,videoplayback,151
3,imagen4.jpg,0.1,48.0,6.5,0.0,0.0,0.0,45.4,videoplayback,151
4,imagen5.jpg,0.1,48.0,6.5,0.0,0.0,0.0,45.4,videoplayback,151
...,...,...,...,...,...,...,...,...,...,...
146,imagen147.jpg,0.0,1.3,98.2,0.0,0.0,0.0,0.5,videoplayback,151
147,imagen148.jpg,0.0,2.1,96.1,0.0,0.1,0.0,1.7,videoplayback,151
148,imagen149.jpg,0.0,0.1,98.9,0.0,0.2,0.0,0.7,videoplayback,151
149,imagen150.jpg,0.0,98.6,1.4,0.0,0.0,0.0,0.1,videoplayback,151
150,imagen151.jpg,0.0,97.4,0.6,0.1,0.0,0.0,1.9,videoplayback,151

In [22]:
df_BD

,Nombre de Imagen,angry,disgust,fear,sad,neutral,surprise,happy,Video,Q_images
0,imagen1.jpg,15.3,54.2,5.8,16.8,7.7,0.1,0.1,test1,360
1,imagen2.jpg,0.0,0.0,0.8,93.8,0.1,0.0,5.3,test1,360
2,imagen3.jpg,0.3,0.0,5.1,0.5,0.5,1.7,92.0,test1,360
3,imagen4.jpg,0.0,0.0,0.1,0.0,0.0,0.0,99.8,test1,360
4,imagen5.jpg,41.1,0.0,0.5,46.1,0.0,0.0,12.3,test1,360
...,...,...,...,...,...,...,...,...,...,...
506,imagen147.jpg,0.0,0.0,0.5,1.3,98.2,0.0,0.0,videoplayback,151
507,imagen148.jpg,0.0,0.0,1.7,2.1,96.1,0.1,0.0,videoplayback,151
508,imagen149.jpg,0.0,0.0,0.7,0.1,98.9,0.2,0.0,videoplayback,151
509,imagen150.jpg,0.0,0.0,0.1,98.6,1.4,0.0,0.0,videoplayback,151
510,imagen151.jpg,0.1,0.0,1.9,97.4,0.6,0.0,0.0,videoplayback,151